/**
 * 成语数据导入脚本
 * 将成语数据批量导入 Supabase 数据库
 * 
 * 运行方式: node scripts/import-idioms.js
 */

const SUPABASE_URL = 'https://gccndjqkglzgpuutyecw.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjY25kanFrZ2x6Z3B1dXR5ZWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0MDE3OTQsImV4cCI6MjA5Mzk3Nzc5NH0.FBuVMuuQa8tVvaLdRrPYq33ehoNSSwVsx7oMxl8rjlQ';

const IDIOMS_DATA = [
  { idiom: "一心一意", explanation: "只有一个心思，没有别的念头。形容专心致志。", difficulty: 1 },
  { idiom: "马到成功", explanation: "战马一到就取得胜利。形容迅速取得成功。", difficulty: 1 },
  { idiom: "心想事成", explanation: "心里想要的都能实现。", difficulty: 1 },
  { idiom: "一帆风顺", explanation: "船帆顺风航行。比喻一切顺利。", difficulty: 1 },
  { idiom: "学海无涯", explanation: "学问像大海一样没有边际。", difficulty: 1 },
  { idiom: "勤学苦练", explanation: "勤奋学习，刻苦训练。", difficulty: 1 },
  { idiom: "自强不息", explanation: "自己努力向上，永不停止。", difficulty: 1 },
  { idiom: "厚德载物", explanation: "道德深厚，能容载万物。", difficulty: 1 },
  { idiom: "知足常乐", explanation: "知道满足就经常快乐。", difficulty: 1 },
  { idiom: "助人为乐", explanation: "把帮助别人当作快乐。", difficulty: 1 },
  { idiom: "日新月异", explanation: "每天都在更新，每月都有变化。", difficulty: 1 },
  { idiom: "天长地久", explanation: "像天和地那样永远长久。", difficulty: 1 },
  { idiom: "春风得意", explanation: "形容人心情愉快，事业发展顺利。", difficulty: 1 },
  { idiom: "秋高气爽", explanation: "形容秋天天气晴朗，空气清新。", difficulty: 1 },
  { idiom: "鸟语花香", explanation: "鸟叫，花香。形容春天的美好景象。", difficulty: 1 },
  { idiom: "五颜六色", explanation: "形容色彩丰富多样。", difficulty: 1 },
  { idiom: "四面八方", explanation: "各个方面，各个地方。", difficulty: 1 },
  { idiom: "七上八下", explanation: "形容心神不安。", difficulty: 1 },
  { idiom: "十全十美", explanation: "完美无缺。", difficulty: 1 },
  { idiom: "百发百中", explanation: "形容射箭或射击准确，每次都命中目标。", difficulty: 1 },
  { idiom: "眉开眼笑", explanation: "形容高兴愉快的样子。", difficulty: 1 },
  { idiom: "手忙脚乱", explanation: "形容做事慌张忙乱。", difficulty: 1 },
  { idiom: "眼高手低", explanation: "要求高而能力低。", difficulty: 1 },
  { idiom: "头头是道", explanation: "形容说话或做事很有条理。", difficulty: 1 },
  { idiom: "平平淡淡", explanation: "形容事物或生活平凡普通。", difficulty: 1 },
  { idiom: "方方面面", explanation: "各个方面。", difficulty: 1 },
  { idiom: "实实在在", explanation: "真实，不虚假。", difficulty: 1 },
  { idiom: "明明白白", explanation: "清楚，明确。", difficulty: 1 },
  { idiom: "认认真真", explanation: "严肃仔细，不马虎。", difficulty: 1 },
  { idiom: "大大方方", explanation: "形容态度自然，不拘束。", difficulty: 1 },
  { idiom: "开开心心", explanation: "非常高兴快乐。", difficulty: 1 },
  { idiom: "慢慢吞吞", explanation: "形容动作很慢。", difficulty: 1 },
  { idiom: "辛辛苦苦", explanation: "非常勤劳辛苦。", difficulty: 1 },
  { idiom: "热热闹闹", explanation: "景象繁盛活跃。", difficulty: 1 },
  { idiom: "安安静静", explanation: "没有声音或不嘈杂。", difficulty: 1 },
  { idiom: "痛痛快快", explanation: "形容尽情舒畅。", difficulty: 1 },
  { idiom: "轻轻松松", explanation: "不感到有负担。", difficulty: 1 },
  { idiom: "马马虎虎", explanation: "形容勉强，凑合。", difficulty: 1 },
  { idiom: "慌慌张张", explanation: "形容匆忙不安。", difficulty: 1 },
  { idiom: "三心二意", explanation: "形容犹豫不决或意志不坚定。", difficulty: 1 },
  { idiom: "五湖四海", explanation: "指全国各地。", difficulty: 1 },
  { idiom: "九牛一毛", explanation: "比喻极其微小。", difficulty: 1 },
  { idiom: "千变万化", explanation: "形容变化极多。", difficulty: 1 },
  { idiom: "无穷无尽", explanation: "没有止境。", difficulty: 1 },
  { idiom: "无法无天", explanation: "形容胡作非为。", difficulty: 1 },
  { idiom: "无忧无虑", explanation: "没有任何忧虑。", difficulty: 1 },
  { idiom: "无边无际", explanation: "形容范围极为广阔。", difficulty: 1 },
  { idiom: "不三不四", explanation: "形容不正派或不像样。", difficulty: 1 },
  { idiom: "不屈不挠", explanation: "形容在困难面前不屈服。", difficulty: 1 },
  { idiom: "不知不觉", explanation: "没有感觉到。", difficulty: 1 },
  { idiom: "大吉大利", explanation: "非常吉祥顺利。", difficulty: 1 },
  { idiom: "大街小巷", explanation: "城镇的各个街道。", difficulty: 1 },
  { idiom: "画龙点睛", explanation: "画龙时点上眼睛。比喻在关键处加一点使整体更生动。", difficulty: 2 },
  { idiom: "胸有成竹", explanation: "画竹子前胸中已有竹子的形象。比喻做事有把握。", difficulty: 2 },
  { idiom: "对牛弹琴", explanation: "对牛弹琴。比喻对不懂的人讲道理。", difficulty: 2 },
  { idiom: "井底之蛙", explanation: "井底的青蛙。比喻见识短浅的人。", difficulty: 2 },
  { idiom: "守株待兔", explanation: "守在树桩旁等兔子撞死。比喻坐等运气。", difficulty: 2 },
  { idiom: "掩耳盗铃", explanation: "捂住耳朵偷铃铛。比喻自己欺骗自己。", difficulty: 2 },
  { idiom: "刻舟求剑", explanation: "在船舷上刻记号找剑。比喻拘泥固执。", difficulty: 2 },
  { idiom: "叶公好龙", explanation: "叶公喜欢龙。比喻表面喜欢实际害怕。", difficulty: 2 },
  { idiom: "狐假虎威", explanation: "狐狸借老虎的威风。比喻依仗他人势力。", difficulty: 2 },
  { idiom: "鹤立鸡群", explanation: "仙鹤站在鸡群中。比喻才能出众。", difficulty: 2 },
  { idiom: "滥竽充数", explanation: "不会吹竽混在乐队里。比喻没有真才实学。", difficulty: 2 },
  { idiom: "亡羊补牢", explanation: "丢失羊后修补羊圈。比喻及时补救。", difficulty: 2 },
  { idiom: "南辕北辙", explanation: "车往南走，车印往北。比喻行动与目标相反。", difficulty: 2 },
  { idiom: "东施效颦", explanation: "东施模仿西施皱眉。比喻盲目模仿。", difficulty: 2 },
  { idiom: "纸上谈兵", explanation: "在纸面上谈论兵法。比喻空谈理论。", difficulty: 2 },
  { idiom: "杯弓蛇影", explanation: "把酒杯中的弓影当作蛇。比喻疑神疑鬼。", difficulty: 2 },
  { idiom: "草木皆兵", explanation: "草和树都当作士兵。形容惊慌时极度紧张。", difficulty: 2 },
  { idiom: "风声鹤唳", explanation: "风和鹤的叫声。形容极度惊慌。", difficulty: 2 },
  { idiom: "卧薪尝胆", explanation: "睡在柴草上尝苦胆。比喻刻苦自励。", difficulty: 2 },
  { idiom: "草船借箭", explanation: "用草船借取箭矢。比喻巧妙借用。", difficulty: 2 },
  { idiom: "望梅止渴", explanation: "看到梅子止住口渴。比喻用空想安慰自己。", difficulty: 2 },
  { idiom: "四面楚歌", explanation: "四面都是楚国的歌声。比喻四面受敌。", difficulty: 2 },
  { idiom: "三顾茅庐", explanation: "三次去茅草屋请诸葛亮。比喻诚心邀请。", difficulty: 2 },
  { idiom: "程门立雪", explanation: "在程颐门前雪中站立。形容尊师重道。", difficulty: 2 },
  { idiom: "凿壁偷光", explanation: "在墙上凿洞借邻居的光读书。形容勤学苦读。", difficulty: 2 },
  { idiom: "悬梁刺股", explanation: "把头发挂在梁上，用锥子刺大腿。形容学习刻苦。", difficulty: 2 },
  { idiom: "韦编三绝", explanation: "编竹简的皮绳断了多次。比喻读书勤奋。", difficulty: 2 },
  { idiom: "废寝忘食", explanation: "顾不得睡觉和吃饭。形容专心努力。", difficulty: 2 },
  { idiom: "学而不厌", explanation: "学习而不满足。形容好学。", difficulty: 2 },
  { idiom: "循序渐进", explanation: "按步骤逐渐推进。", difficulty: 2 },
  { idiom: "举一反三", explanation: "举出一例就能推知其他。", difficulty: 2 },
  { idiom: "触类旁通", explanation: "接触一类事物就能推知其他。", difficulty: 2 },
  { idiom: "事半功倍", explanation: "用一半的力气得到成倍的效果。", difficulty: 2 },
  { idiom: "因材施教", explanation: "根据不同人的资质进行教育。", difficulty: 2 },
  { idiom: "因地制宜", explanation: "根据不同地方的情况制定对策。", difficulty: 2 },
  { idiom: "塞翁失马", explanation: "边塞老人丢失马。比喻祸福无常。", difficulty: 2 },
  { idiom: "未雨绸缪", explanation: "天还没下雨就修好房屋。比喻事先做好准备。", difficulty: 2 },
  { idiom: "画蛇添足", explanation: "画好了蛇又添上脚。比喻多此一举。", difficulty: 2 },
  { idiom: "捕风捉影", explanation: "抓住风和影子。比喻说话做事没有根据。", difficulty: 2 },
  { idiom: "道听途说", explanation: "路上听说的话。比喻没有根据的传闻。", difficulty: 2 },
  { idiom: "三人成虎", explanation: "三个人说街市上有老虎，就使人信以为真。", difficulty: 2 },
  { idiom: "积少成多", explanation: "积累少量东西变成多。", difficulty: 2 },
  { idiom: "滴水穿石", explanation: "一滴水也能穿透石头。比喻坚持不懈。", difficulty: 2 },
  { idiom: "锲而不舍", explanation: "雕刻东西一直进行不停止。比喻坚持不懈。", difficulty: 2 },
  { idiom: "持之以恒", explanation: "长期坚持下去。", difficulty: 2 },
  { idiom: "有始有终", explanation: "有开头也有结尾。", difficulty: 2 },
  { idiom: "半途而废", explanation: "中途停止。比喻做事不能坚持到底。", difficulty: 2 },
  { idiom: "功成名就", explanation: "建立了功绩有了名望。", difficulty: 2 },
  { idiom: "名落孙山", explanation: "名字落在孙山后面。比喻考试不中。", difficulty: 2 },
  { idiom: "名不虚传", explanation: "确实很好，不是空有名声。", difficulty: 2 },
  { idiom: "名副其实", explanation: "名称或名声与实际相符合。", difficulty: 2 },
  { idiom: "表里如一", explanation: "外表和内心一样。形容诚实。", difficulty: 2 },
  { idiom: "言行一致", explanation: "说的和做的一样。", difficulty: 2 },
  { idiom: "口是心非", explanation: "嘴里说的是一套，心里想的是另一套。", difficulty: 2 },
  { idiom: "阳奉阴违", explanation: "表面上服从，暗地里违背。", difficulty: 2 },
  { idiom: "见利忘义", explanation: "见到利益就忘记道义。", difficulty: 2 },
  { idiom: "舍生取义", explanation: "舍弃生命获取正义。", difficulty: 2 },
  { idiom: "舍己为人", explanation: "牺牲自己的利益帮助别人。", difficulty: 2 },
  { idiom: "拾金不昧", explanation: "捡到钱物不隐藏。", difficulty: 2 },
  { idiom: "见义勇为", explanation: "看到正义的事勇敢去做。", difficulty: 2 },
  { idiom: "临危不惧", explanation: "遇到危险不害怕。", difficulty: 2 },
  { idiom: "视死如归", explanation: "把死看作回家一样。形容不怕死。", difficulty: 2 },
  { idiom: "百折不挠", explanation: "无论受多少挫折都不退缩。", difficulty: 2 },
  { idiom: "同舟共济", explanation: "同坐一条船过河。比喻同心协力。", difficulty: 2 },
  { idiom: "齐心协力", explanation: "思想一致，共同努力。", difficulty: 2 },
  { idiom: "万众一心", explanation: "千万人一条心。", difficulty: 2 },
  { idiom: "众志成城", explanation: "众人同心像城墙一样坚固。", difficulty: 2 },
  { idiom: "志同道合", explanation: "志向相同，意见相合。", difficulty: 2 },
  { idiom: "情投意合", explanation: "感情融洽，意见一致。", difficulty: 2 },
  { idiom: "知己知彼", explanation: "了解自己和对方。", difficulty: 2 },
  { idiom: "举世闻名", explanation: "全世界都知道。", difficulty: 2 },
  { idiom: "独一无二", explanation: "只有一个，没有相同的。", difficulty: 2 },
  { idiom: "屈指可数", explanation: "弯着手指就能数过来。形容数量少。", difficulty: 2 },
  { idiom: "不计其数", explanation: "无法计算数量。形容很多。", difficulty: 2 },
  { idiom: "成千上万", explanation: "形容数量很多。", difficulty: 2 },
  { idiom: "堆积如山", explanation: "堆集得像山一样。", difficulty: 2 },
  { idiom: "铺天盖地", explanation: "形容来势猛烈，充满了整个天地。", difficulty: 2 },
  { idiom: "翻天覆地", explanation: "形容变化巨大。", difficulty: 2 },
  { idiom: "沧海桑田", explanation: "大海变成桑田，桑田变成大海。比喻世事变化大。", difficulty: 2 },
  { idiom: "瞬息万变", explanation: "在极短时间里变化很多。", difficulty: 2 },
  { idiom: "一成不变", explanation: "一经形成，永不改变。", difficulty: 2 },
  { idiom: "依然如故", explanation: "仍然像从前一样。", difficulty: 2 },
  { idiom: "原封不动", explanation: "完全保持原样。", difficulty: 2 },
  { idiom: "真相大白", explanation: "真实情况完全清楚了。", difficulty: 2 },
  { idiom: "水落石出", explanation: "水落下去，石头露出来。比喻真相大白。", difficulty: 2 },
  { idiom: "一目了然", explanation: "一眼就能看清楚。", difficulty: 2 },
  { idiom: "显而易见", explanation: "非常明显，容易看清。", difficulty: 2 },
  { idiom: "毋庸置疑", explanation: "不必怀疑。", difficulty: 2 },
  { idiom: "千真万确", explanation: "完全确实。", difficulty: 2 },
  { idiom: "无中生有", explanation: "本来没有凭空捏造。", difficulty: 2 },
  { idiom: "指鹿为马", explanation: "指着鹿说是马。比喻故意颠倒黑白。", difficulty: 2 },
  { idiom: "大同小异", explanation: "大部分相同，小部分不同。", difficulty: 2 },
  { idiom: "截然不同", explanation: "完全不同。", difficulty: 2 },
  { idiom: "天壤之别", explanation: "天和地的差别。比喻差别极大。", difficulty: 2 },
  { idiom: "昙花一现", explanation: "昙花开放时间很短。比喻美好事物不持久。", difficulty: 2 },
  { idiom: "朝三暮四", explanation: "早上三个，晚上四个。比喻反复无常。", difficulty: 2 },
  { idiom: "喜新厌旧", explanation: "喜欢新的，讨厌旧的。", difficulty: 2 },
  { idiom: "斩草除根", explanation: "除草要除根。比喻彻底消除。", difficulty: 2 },
  { idiom: "釜底抽薪", explanation: "从锅底抽出柴火。比喻从根本上解决。", difficulty: 2 },
  { idiom: "雪上加霜", explanation: "雪上又加霜。比喻祸上加祸。", difficulty: 2 },
  { idiom: "落井下石", explanation: "掉进井里又往下扔石头。比喻乘人之危。", difficulty: 2 },
  { idiom: "趁火打劫", explanation: "趁人家失火时抢劫。比喻乘人之危。", difficulty: 2 },
  { idiom: "偷工减料", explanation: "私自减少工序和材料。比喻做事敷衍。", difficulty: 2 },
  { idiom: "得过且过", explanation: "能过就过。比喻胸无大志。", difficulty: 2 },
  { idiom: "挑肥拣瘦", explanation: "挑选肥的或瘦的。比喻挑来挑去。", difficulty: 2 },
  { idiom: "斤斤计较", explanation: "对很小的事都要计较。", difficulty: 2 },
  { idiom: "妙语连珠", explanation: "精彩的话一句接一句。", difficulty: 2 },
  { idiom: "口若悬河", explanation: "说话像河水倾泻。形容口才很好。", difficulty: 2 },
  { idiom: "滔滔不绝", explanation: "说话连续不断。", difficulty: 2 },
  { idiom: "有理不紊", explanation: "有条理，不混乱。", difficulty: 2 },
  { idiom: "井井有条", explanation: "整齐有序。", difficulty: 2 },
  { idiom: "理直气壮", explanation: "理由充分，说话有气势。", difficulty: 2 },
  { idiom: "强词夺理", explanation: "用强辩来掩盖道理。", difficulty: 2 },
  { idiom: "无理取闹", explanation: "没有道理而故意捣乱。", difficulty: 2 },
  { idiom: "乱七八糟", explanation: "非常混乱。", difficulty: 2 },
  { idiom: "根深蒂固", explanation: "基础牢固，不易动摇。", difficulty: 2 },
  { idiom: "美不胜收", explanation: "美好的东西太多，接受不完。", difficulty: 2 },
  { idiom: "琳琅满目", explanation: "比喻美好的事物很多。", difficulty: 2 },
  { idiom: "破釜沉舟", explanation: "打破饭锅，凿沉船只。比喻下决心拼到底。", difficulty: 3 },
  { idiom: "背水一战", explanation: "背靠河水与敌人决战。比喻没有退路。", difficulty: 3 },
  { idiom: "孤注一掷", explanation: "把全部筹码押上。比喻使出全部力量。", difficulty: 3 },
  { idiom: "困兽犹斗", explanation: "被围困的野兽还要搏斗。比喻虽处绝境仍要挣扎。", difficulty: 3 },
  { idiom: "穷途末路", explanation: "路已走完。比喻走投无路。", difficulty: 3 },
  { idiom: "山穷水尽", explanation: "山和水都到了尽头。比喻走投无路。", difficulty: 3 },
  { idiom: "走投无路", explanation: "无路可走。比喻陷入绝境。", difficulty: 3 },
  { idiom: "危机四伏", explanation: "到处都有危险。", difficulty: 3 },
  { idiom: "水深火热", explanation: "像在深水和火中。比喻处境极其艰苦。", difficulty: 3 },
  { idiom: "民不聊生", explanation: "人民无法生活。", difficulty: 3 },
  { idiom: "安居乐业", explanation: "安定地生活，愉快地工作。", difficulty: 3 },
  { idiom: "丰衣足食", explanation: "吃的穿的都很充足。", difficulty: 3 },
  { idiom: "国泰民安", explanation: "国家太平，人民安定。", difficulty: 3 },
  { idiom: "路不拾遗", explanation: "路上没有人捡别人丢失的东西。形容社会风气好。", difficulty: 3 },
  { idiom: "夜不闭户", explanation: "晚上睡觉不关门。形容社会安定。", difficulty: 3 },
  { idiom: "推陈出新", explanation: "去掉旧的，产生新的。", difficulty: 3 },
  { idiom: "焕然一新", explanation: "出现崭新的气象。", difficulty: 3 },
  { idiom: "请君入瓮", explanation: "请人进入瓮中。比喻用对方的方法整治对方。", difficulty: 3 },
  { idiom: "调虎离山", explanation: "使老虎离开山。比喻用计使对方离开原地。", difficulty: 3 },
  { idiom: "声东击西", explanation: "表面上打东边，实际上打西边。", difficulty: 3 },
  { idiom: "围魏救赵", explanation: "围住魏国来救赵国。比喻围攻敌人后方。", difficulty: 3 },
  { idiom: "隔岸观火", explanation: "隔着河看对岸着火。比喻置身事外。", difficulty: 3 },
  { idiom: "门可罗雀", explanation: "门前可以张网捕雀。形容门庭冷落。", difficulty: 3 },
  { idiom: "门庭若市", explanation: "门前像市场一样热闹。形容来人多。", difficulty: 3 },
  { idiom: "车水马龙", explanation: "车像流水，马像游龙。形容热闹景象。", difficulty: 3 },
  { idiom: "络绎不绝", explanation: "连续不断。", difficulty: 3 },
  { idiom: "人山人海", explanation: "人群像山和海。形容人非常多。", difficulty: 3 },
  { idiom: "如火如荼", explanation: "像火一样红，像荼一样白。形容气势旺盛。", difficulty: 3 },
  { idiom: "风起云涌", explanation: "大风起来，云彩涌起。比喻事物发展迅速。", difficulty: 3 },
  { idiom: "气势磅礴", explanation: "气势雄伟盛大。", difficulty: 3 },
  { idiom: "波澜壮阔", explanation: "水波广阔。比喻规模宏伟。", difficulty: 3 },
  { idiom: "势如破竹", explanation: "形势像劈竹子一样。比喻节节胜利。", difficulty: 3 },
  { idiom: "所向披靡", explanation: "风吹到的地方都倒伏。比喻力量强大。", difficulty: 3 },
  { idiom: "所向无敌", explanation: "指到哪里都没有对手。", difficulty: 3 },
  { idiom: "不堪一击", explanation: "经受不了一次打击。", difficulty: 3 },
  { idiom: "孤立无援", explanation: "孤单一人没有援助。", difficulty: 3 },
  { idiom: "束手无策", explanation: "像被捆住手一样没有办法。", difficulty: 3 },
  { idiom: "黔驴技穷", explanation: "贵州的驴子技俩用完了。比喻本领有限。", difficulty: 3 },
  { idiom: "江郎才尽", explanation: "江淹的才能用完了。比喻才思枯竭。", difficulty: 3 },
  { idiom: "班门弄斧", explanation: "在鲁班门前耍斧头。比喻在行家面前卖弄。", difficulty: 3 },
  { idiom: "自不量力", explanation: "不衡量自己的力量。", difficulty: 3 },
  { idiom: "以卵击石", explanation: "用鸡蛋碰石头。比喻自不量力。", difficulty: 3 },
  { idiom: "力不从心", explanation: "心里想做但力量不够。", difficulty: 3 },
  { idiom: "爱莫能助", explanation: "心里同情但无法帮助。", difficulty: 3 },
  { idiom: "鞭长莫及", explanation: "鞭子再长也打不到。比喻力量达不到。", difficulty: 3 },
  { idiom: "全力以赴", explanation: "把全部力量投进去。", difficulty: 3 },
  { idiom: "呕心沥血", explanation: "吐出心，滴出血。形容用尽心血。", difficulty: 3 },
  { idiom: "绞尽脑汁", explanation: "形容用尽心思。", difficulty: 3 },
  { idiom: "深思熟虑", explanation: "深入细致地考虑。", difficulty: 3 },
  { idiom: "深谋远虑", explanation: "计划周密，考虑长远。", difficulty: 3 },
  { idiom: "老谋深算", explanation: "形容人深沉有计谋。", difficulty: 3 },
  { idiom: "神机妙算", explanation: "形容计谋非常高明。", difficulty: 3 },
  { idiom: "料事如神", explanation: "预料事情像神仙一样准确。", difficulty: 3 },
  { idiom: "未卜先知", explanation: "没有占卜就知道。形容有预见。", difficulty: 3 },
  { idiom: "了如指掌", explanation: "了解得像指着手掌。形容非常清楚。", difficulty: 3 },
  { idiom: "明察秋毫", explanation: "能看清最细微的东西。", difficulty: 3 },
  { idiom: "首鼠两端", explanation: "犹豫不决。", difficulty: 4 },
  { idiom: "瞻前顾后", explanation: "看看前面，看看后面。比喻顾虑太多。", difficulty: 4 },
  { idiom: "畏首畏尾", explanation: "怕这怕那。形容顾虑很多。", difficulty: 4 },
  { idiom: "忧心忡忡", explanation: "忧虑不安的样子。", difficulty: 4 },
  { idiom: "惴惴不安", explanation: "恐惧不安的样子。", difficulty: 4 },
  { idiom: "惶惶不安", explanation: "惊慌不安。", difficulty: 4 },
  { idiom: "惊慌失措", explanation: "惊慌得不知道怎么办。", difficulty: 4 },
  { idiom: "六神无主", explanation: "六神没有主宰。形容心慌意乱。", difficulty: 4 },
  { idiom: "心急如焚", explanation: "心里急得像火烧。", difficulty: 4 },
  { idiom: "如坐针毡", explanation: "像坐在针毡上。形容坐立不安。", difficulty: 4 },
  { idiom: "忐忑不安", explanation: "心神不定。", difficulty: 4 },
  { idiom: "诚惶诚恐", explanation: "非常惊慌恐惧。", difficulty: 4 },
  { idiom: "心有余悸", explanation: "事后还感到害怕。", difficulty: 4 },
  { idiom: "谈虎色变", explanation: "谈到老虎就变色。比喻一提到就害怕。", difficulty: 4 },
  { idiom: "闻风丧胆", explanation: "听到一点风声就吓破了胆。", difficulty: 4 },
  { idiom: "望而生畏", explanation: "看了就害怕。", difficulty: 4 },
  { idiom: "犹豫不决", explanation: "拿不定主意。", difficulty: 4 },
  { idiom: "优柔寡断", explanation: "办事犹豫不决。", difficulty: 4 },
  { idiom: "举棋不定", explanation: "下棋不敢落子。比喻犹豫不决。", difficulty: 4 },
  { idiom: "见异思迁", explanation: "看到不同就想变动。", difficulty: 4 },
  { idiom: "反复无常", explanation: "经常变化。", difficulty: 4 },
  { idiom: "变化多端", explanation: "变化很多。", difficulty: 4 },
  { idiom: "高深莫测", explanation: "高深的程度无法测度。", difficulty: 4 },
  { idiom: "深不可测", explanation: "深得无法测量。", difficulty: 4 },
  { idiom: "精益求精", explanation: "好了还要求更好。", difficulty: 4 },
  { idiom: "锦上添花", explanation: "在锦缎上绣花。比喻好上加好。", difficulty: 4 },
  { idiom: "雪中送炭", explanation: "下雪时送炭。比喻帮助及时。", difficulty: 4 },
  { idiom: "乐善好施", explanation: "喜欢做好事，帮助别人。", difficulty: 4 },
  { idiom: "慷慨解囊", explanation: "大方地拿出钱帮助别人。", difficulty: 4 },
  { idiom: "赴汤蹈火", explanation: "即使赴汤蹈火也在所不辞。", difficulty: 4 },
  { idiom: "出生入死", explanation: "从出生到死亡。形容冒着生命危险。", difficulty: 4 },
  { idiom: "冲锋陷阵", explanation: "冲向敌人阵地。", difficulty: 4 },
  { idiom: "身先士卒", explanation: "作战时将帅带头冲在前面。", difficulty: 4 },
  { idiom: "一马当先", explanation: "一马冲在前面。比喻领先。", difficulty: 4 },
  { idiom: "毛遂自荐", explanation: "自我推荐。", difficulty: 4 },
  { idiom: "挺身而出", explanation: "勇敢地站出来。", difficulty: 4 }
];

async function importIdioms() {
  console.log(`开始导入 ${IDIOMS_DATA.length} 条成语数据...`);
  
  let successCount = 0;
  let errorCount = 0;
  
  for (const idiom of IDIOMS_DATA) {
    try {
      const response = await fetch(`${SUPABASE_URL}/rest/v1/idioms`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'apikey': SUPABASE_ANON_KEY,
          'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
          'Prefer': 'return=minimal'
        },
        body: JSON.stringify({
          idiom: idiom.idiom,
          explanation: idiom.explanation,
          difficulty: idiom.difficulty
        })
      });
      
      if (response.ok) {
        successCount++;
        console.log(`✓ ${idiom.idiom}`);
      } else {
        errorCount++;
        console.error(`✗ ${idiom.idiom}: ${response.status}`);
      }
    } catch (error) {
      errorCount++;
      console.error(`✗ ${idiom.idiom}: ${error.message}`);
    }
  }
  
  console.log(`\n导入完成！成功: ${successCount}, 失败: ${errorCount}`);
}

importIdioms();
